### PR TITLE
[WIP] Website fix

### LINKED ISSUE #121: Fix current website
1. Slider
2. Same image size in the project page
3. Fixing image size in specific project page
4. Concise description
5. Re-directing to other chapters

### PR DESCRIPTION
**Pull request by choiboy98**
resolves #121

### CODE REVIEW

File: components/homepage/ourWork.js [hunk 1]
```diff
@@ -8,22 +8,22 @@ import ActionLink from "../actionLink";
 
 const items = [
   <ProjectContainer
-    title="Cut 2 the Case"
-    subtitle="How might we make students feel safer on campus?"
-    image="url('/static/images/projects/c2tc-2/c2tc-2-cover.jpg')"
-    link="/projects?name=c2tc-2"
+    title="Kiva"
+    subtitle="How might we create a single portal where users can easily track their progress and upload documents?"
```
Comment (rgychiu) [inline components/homepage/ourWork.js]: This is too simple and vague description for Kiva. Yes, what we did was create a portal where users can easily track their progress and upload documents, but the overarching problem is much bigger than this. Kiva crowdfunds and distributes many loans worldwide and relies on a network of Field Partners through which they can vet nonprofits, disburse loans, etc. In order to constantly have such a large network, the portfolio managers need to collect financial documents from these Field partners. So yes, what we did was create a single portal where users can easily track their progress and upload documents, but the overarching problem is how do we expedite/simplify the reporting process for loan partners/field partners.

File: data/projects/semesters/sp19/kiva-2.js [hunk 2]
```diff
@@ -5,60 +5,61 @@ const detail = "How might we create a single portal where Field Partners and Por
...
     detail:
-      "Kiva users (portfolio managers) and partners (field partners) can log in to our application and be verified using the security tool developed by our chapter's Product Infrastructure team.",
+      "Kiva users and partners can log in to our application and be verified using the security tool developed by our chapter's Product Infrastructure team.",
     imgPath: "/static/images/projects/kiva-2/kiva2-login.png"
   },
   {
     title: "Field partner dashboard",
     detail:
-      "Required documents are organized by their status, and portfolio managers can review their field partners' documents on this same page, rejecting or approving them to indicate if the documents were filled out properly.",
+      "Required documents are organized by their status, and portfolio managers can reject or approve them to indicate based on their completions.",
```
Comment (rgychiu) [inline data/projects/semesters/sp19/kiva-2.js]: indicate based on their completions sounds a little off to me

File: data/projects/semesters/sp19/gg-2.js [hunk 3]
```diff
@@ -26,45 +27,33 @@ const clientFeatures = [
...
-        "Unguided LDA class creates a model representing the “topics” present in a dataset of non-profit projects. The core purpose of this class is to cluster together new topics rather than classifying projects based on pre-determined topics, thus providing a new perspective on the variety of data.",
+        "Unguided LDA class creates a model representing the “topics” present in a dataset of non-profit projects.",
       imgPath: "/static/images/projects/gg-2/gg2-unguided.png"
     },
-    {
-      title: "Bag Of Words",
-      detail:
-        "Bag of words is a statistical method of classifying documents based off the frequency and relevance of words in a document's text. Using this algorithm, we can predict the themes of an organization to effectively understand their mission based off their websites' text!",
-      imgPath: "/static/images/projects/gg-2/gg2-bow.png"
-    }
```
Comment (rgychiu) [inline data/projects/semesters/sp19/gg-2.js]: What's the reason for deleting Bag of Words and Word Vectors - is it because there's too many tabs on the project page?

**Review by rgychiu — CHANGES_REQUESTED** [review]

**Comment by tko22** [comment]
could you post screenshots, I don't want to run the website (screenshot the entire browser window)

File: data/projects/semesters/sp19/gg-2.js (hunk 3 above)
Comment (choiboy98) [reply data/projects/semesters/sp19/gg-2.js]: There were too many tabs, but also there's already a document vector, so I thought word vector was not too necessary. The reason why I deleted Bag of Words is because I do not think it provides as much information as the other tabs.

**Comment by tko22** [comment]
- Can we make the Chapter Logos 25-40% smaller? And maybe add a little bit more spacing between the "Other Chapters" Title and the logos? 
- Cornell and BU's logos are very similar, maybe separate them with another school instead?
- Georgia Tech and Upenn logos look like they are stretched vertically. I would adjust their height. Tip: look at the original dimensions of the logo and adjust the height accordingly based on the width (if the proportional height is greater than the other logos, make the width smaller and adjust accordingly)

Otherwise, the rest looks great!

File: components/homepage/clientSlider.js [hunk 4]
```diff
@@ -29,29 +29,36 @@ const clients = [
...
-    link: "/projects?name=gg"
+    link: "/projects?name=gg-2"
   },
   {
     name: "Kiva",
     width: 160,
     height: 55,
     logoPath: "/static/images/client_logos/kivalogo.png",
-    link: "/projects?name=kiva-1"
+    link: "/projects?name=kiva-2"
```
Comment (tko22) [inline components/homepage/clientSlider.js]: you could add another kiva logo and link it to `kiva-1` - just place the kiva logos like 2-3 logos away from each other

File: components/homepage/otherChapters.js [hunk 5]
```diff
@@ -0,0 +1,110 @@
...
+export default () => (
+    <Section className="chapters-section">
+        <Row>
+            <h1 className="section-title center" style={{ marginBottom: "50px" }}>
+                Other Chapters
+            </h1>
+        </Row>
+        <Row>
+            <div className="showcase-container">
+            <BackgroundSlider duration={40}>
```
Comment (tko22) [inline components/homepage/otherChapters.js]: good job figuring this out!

File: components/projects/specificProjectPage.js [hunk 6]
```diff
@@ -21,6 +21,7 @@ class SpecificProjectPage extends Component {
           clientLink={project.clientLink}
           githubLink={project.githubLink}
           projectLink={project.projectLink}
+          previousLink={project.previousLink}
```
Comment (tko22) [inline components/projects/specificProjectPage.js]: I like this addition!

**Comment by tko22** [comment]
would love it if you could set up a Zeit Now Auto deployment for just Pull Requests. Essentially, whenever someone makes a PR and makes new commits to it, it would deploy the app based on the branch and post the link in the PR. Then, there would be no need for screenshots! https://zeit.co/docs/v2/integrations/now-for-github/ I've added you to our zeit account, but make sure to not deploy master... because we use surge.sh for that because of domain name stuff with national

check out `circle.yml` for deployment commands. We generate static files with next.js with npm/yarn and then deploy those static files

**Comment by tko22** [comment]
@choiboy98  remember to remove the `[WIP]` bracket from your commit and PR next time you merge :)
